// api/index.js
require("dotenv").config();
const express = require("express");
const fetch = require("node-fetch");
const cors = require("cors");

const app = express();
app.use(express.json());
app.use(cors()); // Allow all origins for simplicity in development

// AI SDK Placeholder - In a real app, you would import and use your AI SDK here.
const getAiSummary = async (flowXml, aiModel) => {
  console.log(`Getting summary from AI model: ${aiModel}`);
  // Replace this with your actual AI SDK call
  // Example: const summary = await aiSdk.summarize(flowXml, { model: aiModel });
  return `This is a summary for the flow, generated by ${aiModel}. It automates record creation and updates.`;
};
const getAiChatReply = async (question, aiModel) => {
  console.log(`Getting chat reply from AI model: ${aiModel}`);
  // Replace with your actual AI SDK call for chat
  return `As ${aiModel}, my response to "${question}" is that this is a powerful feature.`;
};

// --- ENDPOINT 1: Get Initial User and Flow Data ---
app.post("/api/get-initial-data", async (req, res) => {
  const { sessionId, salesforceHost, flowId } = req.body;

  if (!sessionId || !salesforceHost || !flowId) {
    return res.status(400).json({ error: "Missing required Salesforce data." });
  }

  try {
    // 1. Fetch User Details from Salesforce
    const userUrl = `https://${salesforceHost}/services/oauth2/userinfo`;
    const userResponse = await fetch(userUrl, {
      headers: { Authorization: `Bearer ${sessionId}` },
    });
    if (!userResponse.ok)
      throw new Error("Failed to fetch Salesforce user details.");
    const userData = await userResponse.json();
    const username = userData.name;

    // 2. Fetch Flow XML from Salesforce (Example using Tooling API)
    // This query fetches the XML definition of a specific Flow version
    const flowQuery = `SELECT Definition.Source FROM FlowDefinition WHERE DeveloperName = '${flowId}' ORDER BY VersionNumber DESC LIMIT 1`;
    const flowUrl = `https://${salesforceHost}/services/data/v58.0/tooling/query/?q=${encodeURIComponent(
      flowQuery
    )}`;
    const flowResponse = await fetch(flowUrl, {
      headers: { Authorization: `Bearer ${sessionId}` },
    });
    if (!flowResponse.ok)
      throw new Error("Failed to fetch Salesforce flow XML.");
    const flowData = await flowResponse.json();
    const flowXml = flowData.records[0].Definition.Source;

    // 3. Get Summary from AI
    const summary = await getAiSummary(flowXml, "Gemini"); // Default to Gemini for first summary

    // 4. Send combined response
    res.status(200).json({ username, summary });
  } catch (error) {
    console.error("Server Error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

// --- ENDPOINT 2: Handle Chat Messages ---
app.post("/api/chat", async (req, res) => {
  const { question, aiModel } = req.body;

  if (!question || !aiModel) {
    return res.status(400).json({ error: "Missing question or aiModel." });
  }

  try {
    const reply = await getAiChatReply(question, aiModel);
    res.status(200).json({ reply });
  } catch (error) {
    console.error("Server Error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

// Export the app for Vercel
module.exports = app;
