// api/index.js
const express = require('express');
const cors = require('cors');
const app = express();

// Middleware to parse JSON and allow cross-origin requests
app.use(cors());
app.use(express.json());

// --- MOCK AI FUNCTIONS (No real AI SDK needed for testing) ---
const getFakeAiSummary = (flowId, aiModel) => {
    console.log(`[Server] Generating FAKE summary for flow ${flowId} using ${aiModel}`);
    return `This is a FAKE summary for your flow, generated by a mock ${aiModel}. The flow seems to handle new contact creation.`;
};

const getFakeAiChatReply = (question, aiModel) => {
    console.log(`[Server] Generating FAKE chat reply for "${question}" using ${aiModel}`);
    return `As the mock ${aiModel}, my FAKE response to "${question}" is that it sounds like an excellent idea!`;
};

// --- ENDPOINT 1: Get Initial User and Flow Data ---
app.post('/api/get-initial-data', async (req, res) => {
    // In a real app, you'd use this data to hit Salesforce APIs
    const { sessionId, salesforceHost, flowId } = req.body;
    console.log('[Server] Received request for initial data:', { salesforceHost, flowId });

    if (!sessionId || !salesforceHost || !flowId) {
        return res.status(400).json({ error: 'Missing required Salesforce data from the extension.' });
    }

    // --- FAKE DATA RESPONSE ---
    const fakeUsername = "Prateek (from Server)";
    const fakeSummary = getFakeAiSummary(flowId, 'Gemini'); // Default model for initial summary

    res.status(200).json({
        username: fakeUsername,
        summary: fakeSummary
    });
});

// --- ENDPOINT 2: Handle Chat Messages ---
app.post('/api/chat', async (req, res) => {
    const { question, aiModel } = req.body;
    console.log('[Server] Received chat message:', { question, aiModel });

    if (!question || !aiModel) {
        return res.status(400).json({ error: 'Missing question or aiModel.' });
    }

    // --- FAKE DATA RESPONSE ---
    const fakeReply = getFakeAiChatReply(question, aiModel);
    res.status(200).json({ reply: fakeReply });
});

// Export the app for Vercel's serverless environment
module.exports = app;
